name: dtlive
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
#  better_player:
#    path: packages/betterplayer/
  pod_player:
    path: packages/podplayer/
  chewie:
    path: packages/chewie/

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  google_fonts: ^4.0.0
  buttons_tabbar: ^1.3.7
  subtitle_wrapper_package: ^2.1.1
#  better_player:
#  chewie:
  # Players
  # youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^4.0.4
  vimeo_video_player: ^0.0.10
  video_player: ^2.7.0
#  video_player_web_hls: ^1.0.0+3
  # Players
  image_picker: ^1.0.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.1.0
  percent_indicator: ^4.2.3
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  progress_dialog_null_safe: ^1.0.7
  expandable_text: ^2.3.0
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.18.0
  flutter_locales: ^3.0.1
  expandable: ^5.0.1
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.3
  google_sign_in: ^6.1.4
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.4
  onesignal_flutter: ^3.5.1
  intl_phone_field: ^3.2.0
  http: ^0.13.5
  pinput: ^2.2.31
  flutter_html: ^3.0.0-alpha.3
  url_launcher: ^6.1.11
  bottom_navy_bar: ^6.0.0
  shimmer: ^3.0.0
  shimmer_animation: ^2.1.0+1
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  flutter_share: ^2.0.0
  path_provider: ^2.0.15
  path: ^1.8.2
  html: ^0.15.4
  social_share: ^2.3.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  scrollable_positioned_list: ^0.3.8
  pull_to_refresh: ^2.0.0
  permission_handler: ^10.4.1
  flutter_local_notifications: ^15.0.0
  responsive_framework: ^1.0.0
  dropdown_button2: ^2.0.0
  universal_html: ^2.0.9
  js: ^0.6.5
  responsive_grid_list: ^1.3.2
  flutter_cors: ^1.4.0
  device_info_plus: ^8.1.0
  flutter_downloader: ^1.10.2
  random_string: ^2.3.1
  flutter_secure_storage: ^8.0.0
  scrollview_observer: ^1.14.0
  flutter_pagewise: ^2.0.4
  connectivity_plus: ^4.0.1
  marquee: ^2.2.3
  numeral: ^2.0.1
  gradient_borders: ^1.0.0
  screen_protector: ^1.2.0
  sidebarx: ^0.16.0
  another_flushbar:
#  player_video:
  google_mobile_ads:
  wakelock:
#  flutter_vlc_player: ^7.4.0
#  appinio_video_player: ^1.2.2
#  meedu_player: ^0.5.0-nullsafety.0
#  flutter_meedu_media_kit: ^4.2.14


dependency_overrides:
  webview_flutter_wkwebview: '3.5.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets: 
    - assets/
    - assets/images/
    - assets/locales/en.json
    - assets/locales/ar.json
    - assets/locales/hi.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
